name: cilviewer_webapp
channels:
  - conda-forge
dependencies:
- python==3.9
- matplotlib # Optional for more colormaps
- h5py
- numpy
- pyside2
- eqt
- importlib_metadata    # [py<38]
- cil-data >=22.0.0
- pip
- pip:
  # Have to install Trame via pip due to unavailability on conda
  - trame <3, >=2.1.1  # Unpinned worked with version 2.1.1, should work with higher versions.
  - vtk==9.1
