# run: conda env create --file environment.yml
name: cilviewer_webapp
channels:
  - conda-forge
  - ccpi
dependencies:
- python==3.9
- matplotlib # Optional for more colormaps
- h5py
- pip
- schema
- pyyaml
- pip:
  # Have to install Trame via pip due to unavailability on conda
  - trame <3, >=2.1.1  # Unpinned worked with version 2.1.1, should work with higher versions.
  - vtk==9.1
